
version: '3.6'
services:
    db:
        container_name: DOCKERIZED_WORDPRESS_DB
        image: mysql:5.7
        volumes:
            - DOCKERIZED_WORDPRESS_data_db:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        container_name: DOCKERIZED_WORDPRESS_WP
        image: wordpress:latest
        depends_on:
            - db
        ports:
            - 9280:80
        restart: always
        environment:
            ENVIRONMENT: "dev"
            PHP_FPM_CLEAR_ENV: "yes"
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
        volumes:
            - ./plugins:/var/www/html/wp-content/plugins
            - ./themes:/var/www/html/wp-content/themes
            - ./uploads:/var/www/html/wp-content/uploads

    phpmyadmin:
        container_name: DOCKERIZED_WORDPRESS_PHPMYADMIN
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 9080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: mypassword

volumes:
    DOCKERIZED_WORDPRESS_data_db: